DROP SCHEMA IF EXISTS HOTEL_DB;

-- Create Schema HOTEL_DB
CREATE SCHEMA HOTEL_DB;

-- USE HOTEL_DB
USE HOTEL_DB;
CREATE TABLE P_CUSTOMER(
	PCID VARCHAR(50),
    NAME VARCHAR(150),
    AGE INT,
    GOVT_ID VARCHAR(50),
    PHONE VARCHAR(50),
    PRIMARY KEY (PCID)
);
select * from P_CUSTOMER;

CREATE TABLE DEPENDANTS(
	DCID VARCHAR(50),
    NAME VARCHAR(150),
    AGE INT,
    GOVT_ID VARCHAR(50),
    PHONE VARCHAR(50),
    PCID VARCHAR(50) NOT NULL,
    PRIMARY KEY (DCID),
    FOREIGN KEY (PCID)
        REFERENCES P_CUSTOMER (PCID)
        ON DELETE NO ACTION
);

CREATE TABLE ROOMS(
	RID INT,
    FLOOR INT,
    ROOM_TYPE VARCHAR(100),
    NO_OF_BEDS INT,
    PRICE INT,
    OCCUPANCY INT,
    WIFI VARCHAR(20),
    TV VARCHAR(20),
    BREAKFAST VARCHAR(20),
    AC VARCHAR(20),
    PRIMARY KEY(RID)
);


CREATE TABLE OFFERS(
OFFER_CODE VARCHAR(20),
SEASON VARCHAR(50),
DESCRIPTION VARCHAR(150),
DISCOUNTED_PRICE INT,
RID INT NOT NULL,
TYPE VARCHAR(50),
PRIMARY KEY(OFFER_CODE)
);


CREATE TABLE EVENT(
	EVENT_ID VARCHAR(50),
	EVENT_TYPE VARCHAR(50),
    ARRANGEMENTS VARCHAR(100),
    NO_OF_PPL INT,
    PCID VARCHAR(50) NOT NULL,
    RID INT,
    EVENT_DT DATE,
    PRIMARY KEY (EVENT_ID,RID,EVENT_DT),
    FOREIGN KEY (PCID)
        REFERENCES P_CUSTOMER (PCID)
        ON DELETE NO ACTION,
	FOREIGN KEY (RID)
        REFERENCES ROOMS (RID)
        ON DELETE NO ACTION
);


CREATE TABLE PAYMENT(
	PAY_ID VARCHAR(50),
    PAY_TYPE VARCHAR(50),
	PAYMENT_DT timestamp DEFAULT NOW(),
    PRIMARY KEY(PAY_ID)
);

CREATE TABLE BOOKINGS(
	PCID VARCHAR(50),
    RID INT,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    PAY_ID VARCHAR(50),
    FINAL_PRICE INT,
    PRIMARY KEY(PCID,RID,START_DT,END_DT),
    FOREIGN KEY (PCID)
        REFERENCES P_CUSTOMER (PCID)
        ON DELETE NO ACTION,
    FOREIGN KEY (RID)
        REFERENCES ROOMS(RID)
        ON DELETE NO ACTION,
	FOREIGN KEY (PAY_ID)
		REFERENCES PAYMENT(PAY_ID)
);
select * from bookings;
select * from dependants;

select distinct r.rid ,r.room_type, b.START_DT, b.END_DT
from bookings b, rooms r, (select dCID, pcid from dependants d where DCID='123456' OR PCID='123456') AS dependant
where b.rid=r.rid AND dependant.pcid=b.pcid;

show tables;

INSERT INTO OFFERS(OFFER_CODE,SEASON,DESCRIPTION,DISCOUNTED_PRICE,RID,TYPE) VALUES ('SH01','THANKSGIVING','20% OFF ON SELECT ROOMS','32','101','MINI-SUITE');
INSERT INTO OFFERS(OFFER_CODE,SEASON,DESCRIPTION,DISCOUNTED_PRICE,RID,TYPE) VALUES ('SH02','THANKSGIVING','20% OFF ON SELECT ROOMS','40','302','FAMILY-SUITE');
INSERT INTO OFFERS(OFFER_CODE,SEASON,DESCRIPTION,DISCOUNTED_PRICE,RID,TYPE) VALUES ('SH03','THANKSGIVING','20% OFF ON SELECT ROOMS','56','401','MASTER-SUITE');

